work_dir: ./logs/DML/cifar100/mobilenet-resnet32
processor: DML

# dataset
feeder: feeder.cifar100
batch_size: 64
test_batch_size: 64

# model
student: model.mobilenet
teacher: model.resnet32
teacher_model_args:
    option: B
print_model: False

# loss
loss: loss.DMLLoss

# optim
weight_decay: 0.0005
nesterov: True
num_epoch: 200
lr_decay:
    base: 0.1
    policy: MultiStep
    milestones: [60, 120, 180]

# general
save_interval: 10
