work_dir: ./logs/ind/cifar100/mobilenet-A
processor: Processor

# dataset
feeder: cifar100
batch_size: 128
test_batch_size: 64

# model
model: mobilenet
print_model: False

# optim
weight_decay: 0.0002
nesterov: True
num_epoch: 160
lr_decay:
    base: 0.1
    policy: MultiStep
    milestones: [80, 120]

# general
save_interval: 20
