work_dir: ./logs/ind/cifar100/WRN28_10
processor: Processor

# dataset
feeder: feeder.cifar100
batch_size: 128
test_batch_size: 64

# model
model: model.WRN28_10
print_model: False

# optim
weight_decay: 0.0005
nesterov: True
base_lr: 0.1
num_epoch: 160
lr_args:
    policy: MultiStep
    milestones: [80, 120]

# general
save_interval: 20
