work_dir: ./logs/debug
processor: Processor

# dataset
feeder: feeder.cifar100
feeder_args:
    data_dir: ./data/cifar100/
batch_size: 64
test_batch_size: 64

# model
model: model.resnet32
model_args:
    num_classes: 100
print_model: False

# optim
weight_decay: 0.0005
nesterov: True
base_lr: 0.1
num_epoch: 200
lr_args:
    policy: MultiStep
    milestones: [60, 120, 180]
